name: exercise_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.5.8+23

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  csv: ^6.0.0
  path_provider: ^2.1.4
  share_plus: ^12.0.1
  cross_file: ^0.3.4+2
  paged_vertical_calendar: ^1.1.9
  intl: ^0.20.2
  fl_chart: ^0.69.0 # need to upgrade in a min
  font_awesome_flutter: ^10.0.0
  gradient_borders: ^1.0.1
  file_picker: ^10.3.7
  xml: ^6.5.0
  flutter_colorpicker: ^1.1.0
  # vibration: ^1.8.4
  simple_gradient_text: ^1.3.0
  encrypt: ^5.0.3
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  flutter_secure_storage: ^9.2.4
  hive_flutter: ^1.1.0
  flutter_riverpod: ^3.0.3
  hive: ^2.2.3
  flutter_dotenv: ^6.0.0
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Exercises/
    - .env